version: '3'
volumes:
#  web-admin:
  absol-admin:
services:
  nginx:
    image: nginx
    restart: always
    hostname: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d/
      - ./data/files:/opt/resources/
      - absol-admin:/opt/absol-admin
    ports:
      - "41000:80"
  redis:
    image: redis
    restart: always
    ports:
      - "46379:6379"
    hostname: redis
    command: redis-server --requirepass $REDIS_PASSWD
    volumes:
      - ./data/redis:/data
  postgres:
    image: postgres
    restart: always
    hostname: postgres
    ports:
      - "45432:5432"
    environment:
      POSTGRES_PASSWORD: $DB_PASS
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  absol:
    image: hub.wuchuangroup.com/common/jar/absol:latest
    restart: always
    hostname: absol
    volumes:
      - ./logs/absol:/opt/java/logs
    environment:
      DB_PASSWD: $DB_PASS
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_NAME: $DB_NAME_ABOSL
      DB_PORT: $DB_PORT
      REDIS_PASSWD: $REDIS_PASSWD
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      REDIS_DB: $ABSOL_REDIS_DB
      TOKEN_SECONDS: $TOKEN_SECONDS
      SERVER_PORT: $ABSOL_SERVER_PORT
      ABSOL_DOMAIN_CENTER: http://localhost:3000
#      SMS_SECONDS: $SMS_SECONDS
#      ALIPAY_AGENT_ID: $ALIPAY_AGENT_ID
#      ALIPAY_PUBLIC_KEY: $ALIPAY_PUBLIC_KEY
#      ALIPAY_SECRET_KEY: $ALIPAY_SECRET_KEY
#      WE_CHAT_MP_CLIENT_ID: $WE_CHAT_MP_CLIENT_ID
#      WE_CHAT_MP_CLIENT_SECRET: $WE_CHAT_MP_CLIENT_SECRET
#      GITEE_CLIENT_ID: $GITEE_CLIENT_ID
#      GITEE_CLIENT_SECRET: $GITEE_CLIENT_SECRET
#      ABSOL_DOMAIN_USER: $ABSOL_DOMAIN_USER
#      ABSOL_SMS_VERIFY_PAGE: $ABSOL_SMS_VERIFY_PAGE
#      MSG_TMQ_NAME_SPACE: msg_notice
#      MSG_TMQ_NAME_SERVER: 10.0.10.31:49876
#      MSG_TMQ_TOPIC: msg_notice
#      MSG_TMQ_ACCESS_KEY: accesskey
#      MSG_TMQ_SECRET_KEY: secretkey
#      MSG_TMQ_GROUP: msg_notice_group1
    ports:
      - "42000:3000"
  absol-admin:
    image: hub.wuchuangroup.com/internal/absol/web-admin:lastest
    volumes:
      - absol-admin:/opt/webui/
